=== kailashpandey0101/xml-json/target/classes/CustomerSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://www.kailash.org/CustomerSchema" elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.kailash.org/CustomerSchema">

    <complexType name="Customer">
    	<sequence>
    		<element name="customerId" type="int"></element>
    		<element name="custName" type="string"></element>
    		<element name="dateOfBirth" type="date"></element>
    		<element name="annualSalary" type="float"></element>
    		<element name="address" type="tns:Address"></element>
    		<element name="paymentMethod" type="tns:PaymentMethod" minOccurs="1" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>
    
    <complexType name="Address">
    	<sequence>
    		<element name="street" type="string"></element>
    		<element name="city" type="string"></element>
    		<element name="state" type="string"></element>
    		<element name="zip" type="int"></element>
    	</sequence>
    </complexType>
    
    <complexType name="PaymentMethod">
    	<sequence>
    		<element name="cardNumber" type="string"></element>
    		<element name="cardName" type="string"></element>
    		<element name="dateFrom" type="date"></element>
    		<element name="dateType" type="string"></element>
    		<element name="cardType">
    			<simpleType>
    				<restriction base="string">
    					<enumeration value="DEBIT"></enumeration>
    					<enumeration value="CREDIT"></enumeration>
    				</restriction>
    			</simpleType>
    		</element>
    	</sequence>
    </complexType>


    <element name="Customer" type="tns:Customer"></element>
</schema>

=== kailashpandey0101/xml-json/src/main/resources/CustomerXml.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Customer xmlns:tns="http://www.kailash.org/CustomerSchema" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://www.kailash.org/CustomerSchema CustomerSchema.xsd ">
  <tns:customerId>1</tns:customerId>
  <tns:custName>tns:custName</tns:custName>
  <tns:dateOfBirth>2001-01-01</tns:dateOfBirth>
  <tns:annualSalary>0.0</tns:annualSalary>
  <tns:address>
    <tns:street>tns:street</tns:street>
    <tns:city>tns:city</tns:city>
    <tns:state>tns:state</tns:state>
    <tns:zip>0</tns:zip>
  </tns:address>
  <tns:paymentMethod>
    <tns:cardNumber>tns:cardNumber</tns:cardNumber>
    <tns:cardName>tns:cardName</tns:cardName>
    <tns:dateFrom>2001-01-01</tns:dateFrom>
    <tns:dateType>tns:dateType</tns:dateType>
    <tns:cardType>DEBIT</tns:cardType>
  </tns:paymentMethod>
</tns:Customer>
